(defpackage :a (:use :cl) (:nicknames :accessors))
(in-package :a)
(defun :L (&rest _*) (cl:copy-list _*))
(defun :L*(&rest _*) (cl:apply #'cl:list* _*))
(defun :V (&rest _*) (cl:apply #'vector _*))
(defun :0 (_) (cl:elt _ 0))
(defun :1 (_) (cl:elt _ 1))
(defun :2 (_) (cl:elt _ 2))
(defun :3 (_) (cl:elt _ 3))
(defun :4 (_) (cl:elt _ 4))
(defun :5 (_) (cl:elt _ 5))
(defun :6 (_) (cl:elt _ 6))
(defun :7 (_) (cl:elt _ 7))
(defun :8 (_) (cl:elt _ 8))
(defun :9 (_) (cl:elt _ 9))
(defun :1+(_) (cl:cdr _))
(defun :2+(_) (:1+ (:1+ _)))
(defun :3+(_) (:1+ (:2+ _)))
(defun :4+(_) (:1+ (:3+ _)))
(defun :5+(_) (:1+ (:4+ _)))
(defun :6+(_) (:1+ (:5+ _)))
(defun :7+(_) (:1+ (:6+ _)))
(defun :8+(_) (:1+ (:7+ _)))
(defun :9+(_) (:1+ (:8+ _)))
