;;(cl:load "~/quicklisp/setup")
;;(cl:require (cl:quote asdf))
;;(cl:push (cl:truename ".") asdf:*central-registry*)
(ql:quickload '(:woo :clack))
;;(ql:quickload '(:woo :clack) :silent cl:t)
;;(cl:require (cl:quote vfl)) (cl:in-package :vu)
;;(install-macro-chars)
;;(require 'vfl) (cl:in-package :vu)
;;(install-macro-chars)
;;(defun xrun-program (&rest rest)
;;  (uiop:wait-process (uiop:launch-program
;;		      (apply #λconcat-string rest))))
;;(load-file "wi99")
;;(launch)
;;(loop (sleep 60))
